---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
 name: fortune-teller-fortune-service
 namespace: my-apps
 labels:
  apps.tanzu.vmware.com/workload-type: web
  apps.tanzu.vmware.com/has-tests: "true"
  app.kubernetes.io/part-of: fortune
spec:
 params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
 build:
  env:
   - name: BP_JVM_VERSION
     value: "8"
   - name: BP_MAVEN_BUILT_MODULE
     value: "fortune-teller-fortune-service"
 env:
  - name: SPRING_CONFIG_IMPORT
    value: "optional:configtree:${SERVICE_BINDING_ROOT}/spring-properties/"
 serviceClaims:
  - name: eureka
    ref:
     apiVersion: services.apps.tanzu.vmware.com/v1alpha1
     kind: ResourceClaim
     name: eurekaserver-sample
  - name: db
    ref:
     apiVersion: services.apps.tanzu.vmware.com/v1alpha1
     kind: ClassClaim
     name: fortune-database
  - name: spring-properties
    ref:
     apiVersion: services.apps.tanzu.vmware.com/v1alpha1
     kind: ResourceClaim
     name: fortune-config
 source:
  git:
   url: https://github.com/akrishna90/fortune-teller
   ref:
    branch: main