apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
 name: eurekaserver-sample
 namespace: my-apps
spec:
 ref:
  apiVersion: service-registry.spring.apps.tanzu.vmware.com/v1alpha1
  kind: EurekaServer
  name: eurekaserver-sample
  namespace: my-apps
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
 name: fortune-config
 namespace: my-apps
spec:
 ref:
  apiVersion: config.apps.tanzu.vmware.com/v1alpha4
  kind: ConfigurationSlice
  name: fortune-config-slice
  namespace: my-apps
